version: '3.3'

services:
  web: 
    image: node:14
    volumes:
      - ./src:/code  
    working_dir: /code
    command: bash -c "yarn && yarn start"
    environment:
      - NODE_ENV=development
    ports:
      - "3016:3016"
      - "10000-10010:10000-10010"
    networks:
      - back-tier


  nginx:
    networks:
        - back-tier
    image: nginx
    volumes:
      - ./src:/src
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4016:443"
    

networks:
  back-tier:
    driver: bridge