version: '3.3'

services:
  web: 
    image: node:14
    volumes:
      - ./src:/code  
    working_dir: /code
    command: bash -c "yarn && yarn start"
    environment:
      - NODE_ENV=development


  nginx:
    networks:
        - back-tier
    image: nginx
    volumes:
      - ./src:/src
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4016:80"
    

networks:
  back-tier:
    driver: bridge